# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sinarf's journal
email: sinarf@sinarf.org
description: > # this means to ignore newlines until "baseurl:"
    This is my blog, it reflects my and only my point of view, but, since I'm usually right you can agree with me, worshiping is allowed but it is usually a bad idea and you don't have to tell me about it. 
    You disagree? This is your right, don't let anybody tell you otherwise but I'd like to ear about it, might learn something.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://sinarf.github.io" # the base hostname & protocol for your site
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://blog.sinarf.org" # the base hostname & protocol for your site
twitter_username: sinarf
github_username:  sinarf

# Build settings
markdown: kramdown
