# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sinarf's journal
email: sinarf@sinarf.org
description: This is my blog, it reflects my and only my point of view
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.sinarf.org" # the base hostname & protocol for your site
twitter_username: sinarf
github_username:  sinarf
soundcloud_username:  sinarf

# Build settings
markdown: kramdown


<<<<<<< HEAD
=======
theme: jekyll-theme-midnight
>>>>>>> 257e9307c56cd6dafb5d8cbe9d8550fad19271ee
